import { NextResponse } from "next/server";
import { connectDB } from "@/lib/db";
import User from "@/models/user";
import Topic from "@/models/topic";

export async function GET() {
  await connectDB();

  const today = new Date();
  const day = today.getDate();
  const month = today.getMonth(); // 0 = enero

  const users = await User.find();

  for (const user of users) {
    if (!user.fecnac) continue;

    const bday = new Date(user.fecnac);

    const isBirthday =
      bday.getDate() === day && bday.getMonth() === month;

    if (!isBirthday) continue;

    const last = user.lastBirthdayPost
      ? new Date(user.lastBirthdayPost)
      : null;

    if (last && last.getFullYear() === today.getFullYear()) {
      continue; // ya se publicó este año
    }

    // Crear post automático
    await Topic.create({
      title: `🎉 ¡Hoy es el cumpleaños de ${user.username}!`,
      content: `Saluden a ${user.username} en su día especial 🥳`,
      author: user._id,
      autoGenerated: true,
    });

    user.lastBirthdayPost = today;
    await user.save();
  }

  return NextResponse.json({ ok: true });
}
